---

- type: replace
  path: /releases/name=nginx?
  value:
    name: nginx
    version: latest


- type: replace
  path: /instance_groups/name=eap/jobs/name=nginx?
  value:
    name: nginx
    release: nginx
    properties:
      nginx_user: vcap
      nginx_worker_processes: 2
      nginx_worker_connections: 1024
      nginx_servers:
      - server_name: eap.example.com
        docroot: /var/vcap/store/nginx/www/document_root
        port: "443 ssl"
        index: "index.php index.html index.htm"
        access_log: /var/vcap/sys/log/nginx/access.log
        error_log: /var/vcap/sys/log/nginx/error.log
        custom_data: |
                     ssl_certificate /var/vcap/store/eap/server.crt;
                     ssl_certificate_key /var/vcap/store/eap/server.key;
                     ssl_verify_client off;
                     location / {
                       proxy_pass https://localhost:8043/;
                       proxy_ssl_trusted_certificate /var/vcap/store/eap/eapstore.pem;
                       proxy_ssl_verify off;
                     }
      - server_name: eap.example.com
        docroot: /var/vcap/store/nginx/www/document_root
        port: "80"
        index: "index.php index.html index.htm"
        access_log: /var/vcap/sys/log/nginx/access.log
        error_log: /var/vcap/sys/log/nginx/error.log
        custom_data: |
                     return 301 https://$server_name$request_uri;


- type: replace
  path: /instance_groups/name=eap/jobs/name=eapcontroller/properties?/ssl?/key?
  value: |
         -----BEGIN PRIVATE KEY-----
         <snip>
         -----END PRIVATE KEY-----

- type: replace
  path: /instance_groups/name=eap/jobs/name=eapcontroller/properties?/ssl?/crt?
  value: |
         -----BEGIN CERTIFICATE-----
         <snip>
         -----END CERTIFICATE-----
